package com.rslsolution.speakmateai.dto.assistant;

import java.util.List;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request body for {@code POST /api/assistant/message}.
 * The backend is stateless: conversation history lives in the frontend React state
 * and is sent back on every call (bounded to the last few turns here).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AssistantRequest {

	@NotBlank(message = "Message is required")
	private String message;

	/** Opaque id generated by the frontend; echoed back as-is, never persisted. */
	private String sessionId;

	/** Current route in the frontend, used to improve navigation suggestions. */
	private String currentRoute;

	/** Optional recent turns kept in frontend state (role: user | assistant). */
	private List<MessageTurn> history;

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	public static class MessageTurn {
		private String role;
		private String content;
	}
}
