export const ROUTES = Object.freeze({
    // Super Admin Routes
    ADMIN_LOGIN: "/admin/login",
    ADMIN_FORGOT_PASSWORD: "/admin/forgot-password",
    ADMIN_VERIFY_OTP: "/admin/otp-verification",
    ADMIN_RESET_PASSWORD: "/admin/reset-password",
    ADMIN_DASHBOARD: "/admin/dashboard",
    ADMIN_INSIGHTS: "/admin/insights",
    ADMIN_USERS: "/admin/users",
    ADMIN_SCHOOL_USERS: "/admin/school-users",
    ADMIN_ADD_SCHOOL: "/admin/add-school",
    ADMIN_TEACHERS: "/admin/teachers",
    ADMIN_SUBSCRIPTION: "/admin/subscription",
    ADMIN_PROFILE: "/admin/profile",
    ADMIN_SETTINGS: "/admin/settings",
    ADMIN_NOTIFICATIONS: "/admin/notifications",
    NOTIFICATIONS: "/notifications",

    // School Admin Routes
    SCHOOL_ADMIN_LOGIN: "/school-admin/login",
    SCHOOL_ADMIN_FORGOT_PASSWORD: "/school-admin/forgot-password",
    SCHOOL_ADMIN_SET_PASSWORD: "/school-admin/set-password",
    SCHOOL_ADMIN_VERIFY_OTP: "/school-admin/otp-verification",
    SCHOOL_ADMIN_RESET_PASSWORD: "/school-admin/reset-password",
    SCHOOL_ADMIN_DASHBOARD: "/school-admin/dashboard",
    SCHOOL_ADMIN_STUDENTS: "/school-admin/students",
    SCHOOL_ADMIN_TEACHERS: "/school-admin/teachers",
    SCHOOL_ADMIN_RESULTS: "/school-admin/results",
    SCHOOL_ADMIN_INSIGHTS: "/school-admin/insights",
    SCHOOL_ADMIN_PROFILE: "/school-admin/profile",
    SCHOOL_ADMIN_SETTINGS: "/school-admin/settings",
    SCHOOL_ADMIN_NOTIFICATIONS: "/school-admin/notifications",

    // Teacher Routes
    TEACHER_LOGIN: "/teacher/login",
    TEACHER_FORGOT_PASSWORD: "/teacher/forgot-password",
    TEACHER_VERIFY_OTP: "/teacher/otp-verification",
    TEACHER_RESET_PASSWORD: "/teacher/reset-password",
    TEACHER_DASHBOARD: "/teacher/dashboard",
    TEACHER_ANALYTICS: "/teacher/analytics",
    TEACHER_STUDENTS: "/teacher/students",
    TEACHER_STUDENT_DETAILS: "/teacher/students/:studentId",
    TEACHER_REPORTS: "/teacher/reports",
    TEACHER_PROFILE: "/teacher/profile",
    TEACHER_SETTINGS: "/teacher/settings",
    TEACHER_NOTIFICATIONS: "/teacher/notifications",
    VERIFY_EMAIL: "/verify-email",
});

export default ROUTES;
