package com.rslsolution.speakmateai.enums;

public enum NotificationType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    STUDENT_ACTIVITY,
    STUDENT_CREATED,
    STUDENT_UPDATED,
    STUDENT_ASSIGNED,
    TEACHER_CREATED,
    TEACHER_UPDATED,
    TEACHER_ASSIGNED,
    STANDARD_ASSIGNED,
    ASSESSMENT_COMPLETED,
    LESSON_COMPLETED,
    SPEAKING_ACTIVITY_COMPLETED,
    SCHOOL_CREATED,
    SCHOOL_UPDATED,
    SCHOOL_DELETED,
    SYSTEM_EVENT,
    TEACHER_DELETED,
    STUDENT_DELETED
}
