package com.rslsolution.speakmateai.service;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.Test;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.rslsolution.speakmateai.dto.response.TeacherStudentDetailResponse;

public class TeacherServiceImplPdfTest {

    @Test
    public void testValidPdfHeaderSignature() throws Exception {
        try (java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter.getInstance(document, out);
            document.open();
            document.add(new Paragraph("SPEAKMATE AI - STUDENT EVALUATION REPORT"));
            document.close();

            byte[] pdfBytes = out.toByteArray();

            assertNotNull(pdfBytes);
            assertTrue(pdfBytes.length > 50, "PDF size should be non-zero");

            String magicHeader = new String(pdfBytes, 0, 5, StandardCharsets.US_ASCII);
            System.out.println("[TEST] Generated PDF Magic Header: " + magicHeader);
            System.out.println("[TEST] Generated PDF Size: " + pdfBytes.length + " bytes");

            assertTrue(magicHeader.startsWith("%PDF-"), "Generated byte array MUST start with %PDF-");
        }
    }
}
